def gen_Send_Message(name):
    print('''
void {name}_Send_Message({name}_Event_Wrapper e) {
    {name}_Handle_Message(e);
    {name}_Free_Message(e);
}'''.replace('{name}', name))

def generate(ident, names):
    print('''/* This file is generated by smudge.py. Do not edit it. */
#include "multism.h"
#include "{}_ext.h"'''.format(ident))

    for name in names:
        gen_Send_Message(name)

def parse(filename):
    names = []
    with open(filename, 'r') as f:
        for line in f.readlines():
            line = line.strip()
            if line.endswith('{'):
                names.append(line[:-1].strip())

    return names

def main(script, filename):
    names = parse(filename)
    ident = filename.split('.')[0]

    generate(ident, names)

if __name__ == '__main__':
    import sys
    main(*sys.argv)
